"""empty message

Revision ID: 7d452d7d554b
Revises: d0b7c88f3898
Create Date: 2021-10-03 03:22:15.276885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d452d7d554b'
down_revision = 'd0b7c88f3898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('contact', sa.String(length=64), nullable=True),
    sa.Column('body', sa.String(length=2000), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_submission_timestamp'), 'form_submission', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_submission_timestamp'), table_name='form_submission')
    op.drop_table('form_submission')
    # ### end Alembic commands ###
