"""empty message

Revision ID: caf3f44fe827
Revises: 4e4cecac0684
Create Date: 2021-10-03 06:07:51.981906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caf3f44fe827'
down_revision = '4e4cecac0684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_diversity_submission_form_type', table_name='diversity_submission')
    op.drop_column('diversity_submission', 'form_type')
    op.drop_index('ix_hazard_submission_form_type', table_name='hazard_submission')
    op.drop_column('hazard_submission', 'form_type')
    op.drop_index('ix_mental_submission_form_type', table_name='mental_submission')
    op.drop_column('mental_submission', 'form_type')
    op.drop_index('ix_misc_submission_form_type', table_name='misc_submission')
    op.drop_column('misc_submission', 'form_type')
    op.drop_index('ix_physical_submission_form_type', table_name='physical_submission')
    op.drop_column('physical_submission', 'form_type')
    op.drop_index('ix_resource_submission_form_type', table_name='resource_submission')
    op.drop_column('resource_submission', 'form_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_submission', sa.Column('form_type', sa.VARCHAR(length=32), nullable=True))
    op.create_index('ix_resource_submission_form_type', 'resource_submission', ['form_type'], unique=False)
    op.add_column('physical_submission', sa.Column('form_type', sa.VARCHAR(length=32), nullable=True))
    op.create_index('ix_physical_submission_form_type', 'physical_submission', ['form_type'], unique=False)
    op.add_column('misc_submission', sa.Column('form_type', sa.VARCHAR(length=32), nullable=True))
    op.create_index('ix_misc_submission_form_type', 'misc_submission', ['form_type'], unique=False)
    op.add_column('mental_submission', sa.Column('form_type', sa.VARCHAR(length=32), nullable=True))
    op.create_index('ix_mental_submission_form_type', 'mental_submission', ['form_type'], unique=False)
    op.add_column('hazard_submission', sa.Column('form_type', sa.VARCHAR(length=32), nullable=True))
    op.create_index('ix_hazard_submission_form_type', 'hazard_submission', ['form_type'], unique=False)
    op.add_column('diversity_submission', sa.Column('form_type', sa.VARCHAR(length=32), nullable=True))
    op.create_index('ix_diversity_submission_form_type', 'diversity_submission', ['form_type'], unique=False)
    # ### end Alembic commands ###
